2024-09-14 18:45:10,394 : INFO : root : Loading config.
2024-09-14 18:45:10,396 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-09-14 18:45:10,397 : INFO : ConfigProcessor : Loading config from cache: /tmp/228763e525bfce5a238e0b1bd6dd6347.mpf_cache
2024-09-14 18:45:10,425 : INFO : ConfigProcessor : Loading config from cache: /tmp/8973a6dc4f28e221c9999ded5d94a924.mpf_cache
2024-09-14 18:45:10,426 : INFO : ConfigProcessor : Loading config from cache: /tmp/630a60b96e3d9b5031cbb1e5fa5514c1.mpf_cache
2024-09-14 18:45:10,426 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev4
2024-09-14 18:45:10,426 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs/2024-09-14-18-45-10-mpf-mpf.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False, 'full_logfile_path': '/home/pinball/Documents/robowar/logs/2024-09-14-18-45-10-mpf-mpf.log'}
2024-09-14 18:45:10,426 : INFO : Machine : MPF path: /home/pinball/mpfenv/lib/python3.12/site-packages/mpf
2024-09-14 18:45:10,426 : INFO : Machine : Machine path: /home/pinball/Documents/robowar
2024-09-14 18:45:10,426 : INFO : Machine : Platform: linux
2024-09-14 18:45:10,426 : INFO : Machine : Python executable location: /home/pinball/mpfenv/bin/python3
2024-09-14 18:45:10,426 : INFO : Machine : Python version: 3.12.3 (64-bit)
2024-09-14 18:45:10,427 : INFO : Machine : Initializing MPF...
2024-09-14 18:45:10,478 : INFO : lisy : Connecting to /dev/ttyACM0 at 115200bps
2024-09-14 18:45:11,082 : WARNING : lisy : Reset of LISY failed. Did not get a response in 500ms. Will retry.
2024-09-14 18:45:11,584 : WARNING : lisy : Reset of LISY failed. Did not get a response in 500ms. Will retry.
2024-09-14 18:45:12,085 : WARNING : lisy : Reset of LISY failed. Did not get a response in 500ms. Will retry.
2024-09-14 18:45:12,586 : WARNING : lisy : Reset of LISY failed. Did not get a response in 500ms. Will retry.
2024-09-14 18:45:13,088 : WARNING : lisy : Reset of LISY failed. Did not get a response in 500ms. Will retry.
2024-09-14 18:45:13,589 : WARNING : lisy : Reset of LISY failed. Did not get a response in 500ms. Will retry.
2024-09-14 18:45:14,090 : WARNING : lisy : Reset of LISY failed. Did not get a response in 500ms. Will retry.
2024-09-14 18:45:14,591 : WARNING : lisy : Reset of LISY failed. Did not get a response in 500ms. Will retry.
2024-09-14 18:45:15,093 : WARNING : lisy : Reset of LISY failed. Did not get a response in 500ms. Will retry.
2024-09-14 18:45:15,595 : WARNING : lisy : Reset of LISY failed. Did not get a response in 500ms. Will retry.
2024-09-14 18:45:16,097 : WARNING : lisy : Reset of LISY failed. Did not get a response in 500ms. Will retry.
2024-09-14 18:45:16,598 : WARNING : lisy : Reset of LISY failed. Did not get a response in 500ms. Will retry.
2024-09-14 18:45:17,100 : WARNING : lisy : Reset of LISY failed. Did not get a response in 500ms. Will retry.
2024-09-14 18:45:17,231 : INFO : Machine : Starting the main run loop.
2024-09-14 18:45:17,231 : INFO : Machine : Shutting down...
2024-09-14 18:45:17,231 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2024-09-14 18:45:17,233 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished name='Task-1' coro=<MachineController.initialize() done, defined at /home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/machine.py:245> exception=IncompleteReadError('0 bytes read on a total of 1 expected bytes')>
Traceback (most recent call last):
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/machine.py", line 247, in initialize
    await self.initialize_core_and_hardware()
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/machine.py", line 243, in initialize_core_and_hardware
    await self._initialize_platforms()
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/machine.py", line 333, in _initialize_platforms
    result.result()
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/platforms/lisy/lisy.py", line 413, in initialize
    return_code = await asyncio.wait_for(self._read_byte(), timeout=0.5)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 520, in wait_for
    return await fut
           ^^^^^^^^^
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/platforms/lisy/lisy.py", line 816, in _read_byte
    data = await self._reader.readexactly(1)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/streams.py", line 750, in readexactly
    raise exceptions.IncompleteReadError(incomplete, n)
asyncio.exceptions.IncompleteReadError: 0 bytes read on a total of 1 expected bytes
2024-09-14 18:45:17,334 : INFO : root : MPF run loop ended.
