2024-09-18 14:30:04,031 : INFO : root : Loading config.
2024-09-18 14:30:04,033 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-09-18 14:30:04,033 : INFO : ConfigProcessor : Loading config from cache: /tmp/ce9187e7529af622f3b6e40d00abcf94.mpf_cache
2024-09-18 14:30:04,063 : INFO : ConfigProcessor : Loading config from cache: /tmp/8973a6dc4f28e221c9999ded5d94a924.mpf_cache
2024-09-18 14:30:04,063 : INFO : ConfigProcessor : Loading config from cache: /tmp/630a60b96e3d9b5031cbb1e5fa5514c1.mpf_cache
2024-09-18 14:30:04,064 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev4
2024-09-18 14:30:04,064 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs/2024-09-18-14-30-04-mpf-mpf.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False, 'full_logfile_path': '/home/pinball/Documents/Robowar/logs/2024-09-18-14-30-04-mpf-mpf.log'}
2024-09-18 14:30:04,064 : INFO : Machine : MPF path: /home/pinball/mpfenv/lib/python3.12/site-packages/mpf
2024-09-18 14:30:04,064 : INFO : Machine : Machine path: /home/pinball/Documents/Robowar
2024-09-18 14:30:04,064 : INFO : Machine : Platform: linux
2024-09-18 14:30:04,064 : INFO : Machine : Python executable location: /home/pinball/mpfenv/bin/python3
2024-09-18 14:30:04,064 : INFO : Machine : Python version: 3.12.3 (64-bit)
2024-09-18 14:30:04,064 : INFO : Machine : Initializing MPF...
2024-09-18 14:30:04,108 : INFO : lisy : Connecting to /dev/ttyACM0 at 115200bps
2024-09-18 14:30:04,216 : INFO : EventManager : Event: ======'machine_var_lisy_hardware'====== Args={'value': 'LISY80', 'prev_value': None, 'change': True}
2024-09-18 14:30:04,216 : INFO : EventManager : Event: ======'machine_var_lisy_version'====== Args={'value': '5.26 ', 'prev_value': None, 'change': True}
2024-09-18 14:30:04,216 : INFO : EventManager : Event: ======'machine_var_lisy_api_version'====== Args={'value': b'0.09', 'prev_value': None, 'change': True}
2024-09-18 14:30:04,295 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2024-09-18 14:30:04,311 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2024-09-18 14:30:04,311 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev4', 'prev_value': None, 'change': True}
2024-09-18 14:30:04,311 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev4, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2024-09-18 14:30:04,312 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.12.3', 'prev_value': None, 'change': True}
2024-09-18 14:30:04,313 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Linux-6.8.0-38-generic-x86_64-with-glibc2.39', 'prev_value': None, 'change': True}
2024-09-18 14:30:04,313 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Linux', 'prev_value': None, 'change': True}
2024-09-18 14:30:04,313 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '6.8.0-38-generic', 'prev_value': None, 'change': True}
2024-09-18 14:30:04,313 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '#38-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun  7 15:25:01 UTC 2024', 'prev_value': None, 'change': True}
2024-09-18 14:30:04,314 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'x86_64', 'prev_value': None, 'change': True}
2024-09-18 14:30:04,314 : INFO : EventManager : Event: ======'machine_var_log_file_path'====== Args={'value': '/home/pinball/Documents/Robowar/logs/2024-09-18-14-30-04-mpf-mpf.log', 'prev_value': None, 'change': True}
2024-09-18 14:30:04,314 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2024-09-18 14:30:04,332 : WARNING : segment_display.upper_display : Segment display update_method will default to 'replace' in a future MPF release. You have no config value specified and are currently getting 'stack' for backwards compatibility. To avoid a breaking change, please set 'update_method: "stack"' in your segment display config.
2024-09-18 14:30:04,332 : WARNING : segment_display.lower_display : Segment display update_method will default to 'replace' in a future MPF release. You have no config value specified and are currently getting 'stack' for backwards compatibility. To avoid a breaking change, please set 'update_method: "stack"' in your segment display config.
2024-09-18 14:30:04,346 : INFO : EventManager : Event: ======'init_phase_2'====== Args={}
2024-09-18 14:30:04,347 : INFO : SwitchController : Found active switch: ('40', <mpf.platforms.lisy.lisy.LisyHardwarePlatform object at 0x7a0150c80b90>) <switch.s_1_top_target>
2024-09-18 14:30:04,348 : INFO : ball_device.bd_drain : BCH: Initial count: 0
2024-09-18 14:30:04,348 : INFO : ball_device.bd_drain : State: idle
2024-09-18 14:30:04,349 : INFO : ball_device.bd_trough : BCH: Initial count: 0
2024-09-18 14:30:04,349 : INFO : ball_device.bd_trough : State: idle
2024-09-18 14:30:04,349 : ERROR : asyncio : Task exception was never retrieved
future: <Task finished name='Task-135' coro=<BallDevice._initialize_async() done, defined at /home/pinball/mpfenv/lib/python3.12/site-packages/mpf/devices/ball_device/ball_device.py:196> exception=ConfigFileError('Config validation error: Entry ball_device_counter_ball_switches:ball_device_counter_ball_switches:ball_switches = "s_plunger_lane" is not valid. Device "s_plunger_lane" not found in "switches:" section in your config.')>
Traceback (most recent call last):
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/devices/ball_device/ball_device.py", line 198, in _initialize_async
    await self.ball_count_handler.initialize()
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/devices/ball_device/ball_count_handler.py", line 92, in initialize
    self.counter = counter_class(self.ball_device, self.ball_device.config.get("counter", {}))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/devices/ball_device/switch_counter.py", line 27, in __init__
    self.config = self.machine.config_validator.validate_config("ball_device_counter_ball_switches", self.config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/config_validator.py", line 204, in _validate_config
    processed_config[k] = self.validate_config_item(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/config_validator.py", line 256, in validate_config_item
    new_list.append(self.validate_item(i, validation, validation_failure_info))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/config_validator.py", line 699, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/config_validator.py", line 413, in _validate_type_machine
    raise self.validation_error(item, validation_failure_info,
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry ball_device_counter_ball_switches:ball_device_counter_ball_switches:ball_switches = "s_plunger_lane" is not valid. Device "s_plunger_lane" not found in "switches:" section in your config. Error Code: CFE-ConfigValidator-6 (https://missionpinball.org/logs)
2024-09-18 14:30:04,356 : INFO : EventManager : Event: ======'init_phase_3'====== Args={}
2024-09-18 14:30:04,357 : INFO : Machine : Starting the main run loop.
2024-09-18 14:30:04,357 : INFO : EventManager : Event: ======'init_phase_4'====== Args={}
2024-09-18 14:30:04,358 : INFO : Machine : Shutting down...
2024-09-18 14:30:04,358 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2024-09-18 14:30:04,358 : ERROR : root : no running event loop
Traceback (most recent call last):
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/commands/game.py", line 240, in __init__
    self.machine.run()
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/machine.py", line 689, in run
    self._run_loop()
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/machine.py", line 789, in _run_loop
    self._crash_shutdown()
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/machine.py", line 734, in _crash_shutdown
    self._do_stop()
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/machine.py", line 724, in _do_stop
    self.events.process_event_queue()
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/events.py", line 842, in process_event_queue
    self._process_queue_event(event=event[0],
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/events.py", line 783, in _process_queue_event
    task = asyncio.create_task(self._run_handlers_sequential(event, callback, kwargs))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/tasks.py", line 417, in create_task
    loop = events.get_running_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: no running event loop
