2024-09-18 14:01:59,592 : INFO : root : Loading config.
2024-09-18 14:01:59,594 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-09-18 14:01:59,594 : WARNING : ConfigProcessor : Config file in cache changed: /home/pinball/Documents/Robowar/config/config.yaml
2024-09-18 14:01:59,594 : INFO : ConfigProcessor : Loading config from file /home/pinball/mpfenv/lib/python3.12/site-packages/mpf/mpfconfig.yaml.
2024-09-18 14:01:59,603 : INFO : ConfigProcessor : Loading config: /home/pinball/mpfenv/lib/python3.12/site-packages/mpf/mpfconfig.yaml
2024-09-18 14:01:59,603 : INFO : ConfigProcessor : Loading config from file /home/pinball/Documents/Robowar/config/config.yaml.
2024-09-18 14:01:59,604 : INFO : ConfigProcessor : Loading config: /home/pinball/Documents/Robowar/config/config.yaml
2024-09-18 14:01:59,606 : INFO : ConfigProcessor : Loading config: /home/pinball/Documents/Robowar/config/switches.yaml
2024-09-18 14:01:59,607 : INFO : ConfigProcessor : Loading config: /home/pinball/Documents/Robowar/config/coils.yaml
2024-09-18 14:01:59,608 : INFO : ConfigProcessor : Loading config: /home/pinball/Documents/Robowar/config/displays.yaml
2024-09-18 14:01:59,610 : INFO : ConfigProcessor : Loading config: /home/pinball/Documents/Robowar/config/lamps.yaml
2024-09-18 14:01:59,611 : INFO : ConfigProcessor : Config file cache created: /tmp/ce9187e7529af622f3b6e40d00abcf94.mpf_cache
2024-09-18 14:01:59,638 : INFO : ConfigProcessor : Loading config from cache: /tmp/8973a6dc4f28e221c9999ded5d94a924.mpf_cache
2024-09-18 14:01:59,639 : INFO : ConfigProcessor : Loading config from cache: /tmp/630a60b96e3d9b5031cbb1e5fa5514c1.mpf_cache
2024-09-18 14:01:59,639 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev4
2024-09-18 14:01:59,639 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs/2024-09-18-14-01-59-mpf-mpf.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False, 'full_logfile_path': '/home/pinball/Documents/Robowar/logs/2024-09-18-14-01-59-mpf-mpf.log'}
2024-09-18 14:01:59,639 : INFO : Machine : MPF path: /home/pinball/mpfenv/lib/python3.12/site-packages/mpf
2024-09-18 14:01:59,639 : INFO : Machine : Machine path: /home/pinball/Documents/Robowar
2024-09-18 14:01:59,639 : INFO : Machine : Platform: linux
2024-09-18 14:01:59,639 : INFO : Machine : Python executable location: /home/pinball/mpfenv/bin/python3
2024-09-18 14:01:59,639 : INFO : Machine : Python version: 3.12.3 (64-bit)
2024-09-18 14:01:59,640 : INFO : Machine : Initializing MPF...
2024-09-18 14:01:59,691 : INFO : lisy : Connecting to /dev/ttyACM0 at 115200bps
2024-09-18 14:01:59,804 : INFO : EventManager : Event: ======'machine_var_lisy_hardware'====== Args={'value': 'LISY80', 'prev_value': None, 'change': True}
2024-09-18 14:01:59,804 : INFO : EventManager : Event: ======'machine_var_lisy_version'====== Args={'value': '5.26 ', 'prev_value': None, 'change': True}
2024-09-18 14:01:59,804 : INFO : EventManager : Event: ======'machine_var_lisy_api_version'====== Args={'value': b'0.09', 'prev_value': None, 'change': True}
2024-09-18 14:01:59,885 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2024-09-18 14:01:59,902 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2024-09-18 14:01:59,903 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev4', 'prev_value': None, 'change': True}
2024-09-18 14:01:59,903 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev4, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2024-09-18 14:01:59,903 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.12.3', 'prev_value': None, 'change': True}
2024-09-18 14:01:59,905 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Linux-6.8.0-38-generic-x86_64-with-glibc2.39', 'prev_value': None, 'change': True}
2024-09-18 14:01:59,905 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Linux', 'prev_value': None, 'change': True}
2024-09-18 14:01:59,905 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '6.8.0-38-generic', 'prev_value': None, 'change': True}
2024-09-18 14:01:59,905 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '#38-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun  7 15:25:01 UTC 2024', 'prev_value': None, 'change': True}
2024-09-18 14:01:59,905 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'x86_64', 'prev_value': None, 'change': True}
2024-09-18 14:01:59,905 : INFO : EventManager : Event: ======'machine_var_log_file_path'====== Args={'value': '/home/pinball/Documents/Robowar/logs/2024-09-18-14-01-59-mpf-mpf.log', 'prev_value': None, 'change': True}
2024-09-18 14:01:59,905 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2024-09-18 14:01:59,913 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...ight,driver')>) at /home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/events.py:124
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...ight,driver')>) at /home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/events.py:124>
Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/events.py", line 127, in _async_handler_done
    future.result()
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/device_manager.py", line 88, in _load_device_modules
    self.load_devices_config(validate=True)
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/device_manager.py", line 146, in load_devices_config
    config[device_name] = collection[device_name].validate_and_parse_config(config[device_name], False)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/devices/digital_output.py", line 80, in validate_and_parse_config
    config = super().validate_and_parse_config(config, is_mode_config, debug_prefix)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/device.py", line 108, in validate_and_parse_config
    self.machine.config_validator.validate_config(
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/config_validator.py", line 204, in _validate_config
    processed_config[k] = self.validate_config_item(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/config_validator.py", line 243, in validate_config_item
    return self.validate_item(item, validation, validation_failure_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/config_validator.py", line 699, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/config_validator.py", line 390, in _validate_type_enum
    raise self.validation_error(
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry digital_outputs:game_over_relay:type = "coil" is not valid. Entry "coil" is not valid for enum. Valid values are: light,driver Error Code: CFE-ConfigValidator-5 (https://missionpinball.org/logs)
2024-09-18 14:01:59,914 : INFO : Machine : Starting the main run loop.
2024-09-18 14:01:59,915 : INFO : Machine : Shutting down...
2024-09-18 14:01:59,915 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2024-09-18 14:02:01,019 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/machine.py", line 793, in _run_loop
    raise self._exception['exception']
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/events.py", line 127, in _async_handler_done
    future.result()
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/device_manager.py", line 88, in _load_device_modules
    self.load_devices_config(validate=True)
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/device_manager.py", line 146, in load_devices_config
    config[device_name] = collection[device_name].validate_and_parse_config(config[device_name], False)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/devices/digital_output.py", line 80, in validate_and_parse_config
    config = super().validate_and_parse_config(config, is_mode_config, debug_prefix)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/device.py", line 108, in validate_and_parse_config
    self.machine.config_validator.validate_config(
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/config_validator.py", line 204, in _validate_config
    processed_config[k] = self.validate_config_item(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/config_validator.py", line 243, in validate_config_item
    return self.validate_item(item, validation, validation_failure_info)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/config_validator.py", line 699, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/config_validator.py", line 390, in _validate_type_enum
    raise self.validation_error(
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry digital_outputs:game_over_relay:type = "coil" is not valid. Entry "coil" is not valid for enum. Valid values are: light,driver Error Code: CFE-ConfigValidator-5 (https://missionpinball.org/logs)
2024-09-18 14:02:01,023 : INFO : root : MPF run loop ended.
