2024-09-18 14:06:33,135 : INFO : root : Loading config.
2024-09-18 14:06:33,138 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-09-18 14:06:33,139 : INFO : ConfigProcessor : Loading config from cache: /tmp/ce9187e7529af622f3b6e40d00abcf94.mpf_cache
2024-09-18 14:06:33,139 : WARNING : ConfigProcessor : Config file in cache changed: /home/pinball/Documents/Robowar/config/coils.yaml
2024-09-18 14:06:33,139 : INFO : ConfigProcessor : Loading config from file /home/pinball/mpfenv/lib/python3.12/site-packages/mpf/mpfconfig.yaml.
2024-09-18 14:06:33,148 : INFO : ConfigProcessor : Loading config: /home/pinball/mpfenv/lib/python3.12/site-packages/mpf/mpfconfig.yaml
2024-09-18 14:06:33,149 : INFO : ConfigProcessor : Loading config from file /home/pinball/Documents/Robowar/config/config.yaml.
2024-09-18 14:06:33,149 : INFO : ConfigProcessor : Loading config: /home/pinball/Documents/Robowar/config/config.yaml
2024-09-18 14:06:33,152 : INFO : ConfigProcessor : Loading config: /home/pinball/Documents/Robowar/config/switches.yaml
2024-09-18 14:06:33,152 : INFO : ConfigProcessor : Loading config: /home/pinball/Documents/Robowar/config/coils.yaml
2024-09-18 14:06:33,154 : INFO : ConfigProcessor : Loading config: /home/pinball/Documents/Robowar/config/displays.yaml
2024-09-18 14:06:33,156 : INFO : ConfigProcessor : Loading config: /home/pinball/Documents/Robowar/config/lamps.yaml
2024-09-18 14:06:33,158 : INFO : ConfigProcessor : Config file cache created: /tmp/ce9187e7529af622f3b6e40d00abcf94.mpf_cache
2024-09-18 14:06:33,193 : INFO : ConfigProcessor : Loading config from cache: /tmp/8973a6dc4f28e221c9999ded5d94a924.mpf_cache
2024-09-18 14:06:33,193 : INFO : ConfigProcessor : Loading config from cache: /tmp/630a60b96e3d9b5031cbb1e5fa5514c1.mpf_cache
2024-09-18 14:06:33,193 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev4
2024-09-18 14:06:33,193 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs/2024-09-18-14-06-33-mpf-mpf.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False, 'full_logfile_path': '/home/pinball/Documents/Robowar/logs/2024-09-18-14-06-33-mpf-mpf.log'}
2024-09-18 14:06:33,193 : INFO : Machine : MPF path: /home/pinball/mpfenv/lib/python3.12/site-packages/mpf
2024-09-18 14:06:33,193 : INFO : Machine : Machine path: /home/pinball/Documents/Robowar
2024-09-18 14:06:33,193 : INFO : Machine : Platform: linux
2024-09-18 14:06:33,193 : INFO : Machine : Python executable location: /home/pinball/mpfenv/bin/python3
2024-09-18 14:06:33,194 : INFO : Machine : Python version: 3.12.3 (64-bit)
2024-09-18 14:06:33,194 : INFO : Machine : Initializing MPF...
2024-09-18 14:06:33,250 : INFO : lisy : Connecting to /dev/ttyACM0 at 115200bps
2024-09-18 14:06:33,359 : INFO : EventManager : Event: ======'machine_var_lisy_hardware'====== Args={'value': 'LISY80', 'prev_value': None, 'change': True}
2024-09-18 14:06:33,360 : INFO : EventManager : Event: ======'machine_var_lisy_version'====== Args={'value': '5.26 ', 'prev_value': None, 'change': True}
2024-09-18 14:06:33,360 : INFO : EventManager : Event: ======'machine_var_lisy_api_version'====== Args={'value': b'0.09', 'prev_value': None, 'change': True}
2024-09-18 14:06:33,413 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2024-09-18 14:06:33,422 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2024-09-18 14:06:33,423 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev4', 'prev_value': None, 'change': True}
2024-09-18 14:06:33,423 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev4, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2024-09-18 14:06:33,423 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.12.3', 'prev_value': None, 'change': True}
2024-09-18 14:06:33,424 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Linux-6.8.0-38-generic-x86_64-with-glibc2.39', 'prev_value': None, 'change': True}
2024-09-18 14:06:33,424 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Linux', 'prev_value': None, 'change': True}
2024-09-18 14:06:33,424 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '6.8.0-38-generic', 'prev_value': None, 'change': True}
2024-09-18 14:06:33,424 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '#38-Ubuntu SMP PREEMPT_DYNAMIC Fri Jun  7 15:25:01 UTC 2024', 'prev_value': None, 'change': True}
2024-09-18 14:06:33,424 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'x86_64', 'prev_value': None, 'change': True}
2024-09-18 14:06:33,424 : INFO : EventManager : Event: ======'machine_var_log_file_path'====== Args={'value': '/home/pinball/Documents/Robowar/logs/2024-09-18-14-06-33-mpf-mpf.log', 'prev_value': None, 'change': True}
2024-09-18 14:06:33,424 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2024-09-18 14:06:33,427 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...dictionary.")>) at /home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/events.py:124
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...dictionary.")>) at /home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/events.py:124>
Traceback (most recent call last):
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/events.py", line 127, in _async_handler_done
    future.result()
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/device_manager.py", line 83, in _load_device_modules
    self.create_devices(collection_name, config)
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/device_manager.py", line 123, in create_devices
    self.raise_config_error("Device {}:'{}' does not have a valid config. Expected a dictionary.".format(
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/logging.py", line 174, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in DeviceManager: Device coils:'default_pulse_ms' does not have a valid config. Expected a dictionary. Context: coils.default_pulse_ms Error Code: CFE-DeviceManager-3 (https://missionpinball.org/logs)
2024-09-18 14:06:33,428 : INFO : Machine : Starting the main run loop.
2024-09-18 14:06:33,428 : INFO : Machine : Shutting down...
2024-09-18 14:06:33,429 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2024-09-18 14:06:34,532 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/machine.py", line 793, in _run_loop
    raise self._exception['exception']
  File "/usr/lib/python3.12/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/events.py", line 127, in _async_handler_done
    future.result()
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/device_manager.py", line 83, in _load_device_modules
    self.create_devices(collection_name, config)
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/device_manager.py", line 123, in create_devices
    self.raise_config_error("Device {}:'{}' does not have a valid config. Expected a dictionary.".format(
  File "/home/pinball/mpfenv/lib/python3.12/site-packages/mpf/core/logging.py", line 174, in raise_config_error
    raise ConfigFileError(msg, error_no, self.log.name if self.log else "", context, self._url_base) \
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in DeviceManager: Device coils:'default_pulse_ms' does not have a valid config. Expected a dictionary. Context: coils.default_pulse_ms Error Code: CFE-DeviceManager-3 (https://missionpinball.org/logs)
2024-09-18 14:06:34,535 : INFO : root : MPF run loop ended.
