2024-09-17 15:30:55,973 : INFO : root : Loading config.
2024-09-17 15:30:55,976 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-09-17 15:30:55,976 : INFO : ConfigProcessor : Loading config from cache: C:\Users\BRICE~1.ROU\AppData\Local\Temp\c22ae324d2bb5220608e2bc7ef80bf3a.mpf_cache
2024-09-17 15:30:56,342 : INFO : ConfigProcessor : Loading config from cache: C:\Users\BRICE~1.ROU\AppData\Local\Temp\d71cc0065cf3b986b341b4b3acf7151b.mpf_cache
2024-09-17 15:30:56,343 : INFO : ConfigProcessor : Loading config from cache: C:\Users\BRICE~1.ROU\AppData\Local\Temp\08ed8ef6bbf541ff70cecc6b77fe1bdf.mpf_cache
2024-09-17 15:30:56,343 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev4
2024-09-17 15:30:56,343 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2024-09-17-15-30-55-mpf-C-CRI-BUR2-A13.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'full_logfile_path': 'C:\\Users\\brice.rouanet\\Documents\\GitHub\\Robowar\\logs\\2024-09-17-15-30-55-mpf-C-CRI-BUR2-A13.log'}
2024-09-17 15:30:56,343 : INFO : Machine : MPF path: C:\Users\brice.rouanet\Documents\mpf\mpf
2024-09-17 15:30:56,343 : INFO : Machine : Machine path: C:\Users\brice.rouanet\Documents\GitHub\Robowar
2024-09-17 15:30:56,343 : INFO : Machine : Platform: win32
2024-09-17 15:30:56,343 : INFO : Machine : Python executable location: C:\Users\brice.rouanet\Documents\mpfenv\Scripts\python.exe
2024-09-17 15:30:56,343 : INFO : Machine : Python version: 3.11.9 (64-bit)
2024-09-17 15:30:56,344 : INFO : Machine : Initializing MPF...
2024-09-17 15:30:56,752 : INFO : lisy : Connecting to /dev/ttyACM0 at 115200bps
2024-09-17 15:30:56,753 : WARNING : lisy : Could not import terminos (this is ok on windows).
2024-09-17 15:30:56,753 : ERROR : asyncio : Fatal write error on serial transport
protocol: <asyncio.streams.StreamReaderProtocol object at 0x0000020701301090>
transport: SerialTransport(<ProactorEventLoop running=True closed=False debug=False>, <asyncio.streams.StreamReaderProtocol object at 0x0000020701301090>, Serial<id=0x2070347c700, open=False>(port='/dev/ttyACM0', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=0, xonxoff=False, rtscts=False, dsrdtr=False))
Traceback (most recent call last):
  File "C:\Users\brice.rouanet\Documents\mpfenv\Lib\site-packages\serial_asyncio\__init__.py", line 290, in _poll_read
    if self.serial.in_waiting:
       ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brice.rouanet\Documents\mpfenv\Lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (OSError(9, 'Descripteur non valide', None, 6))
2024-09-17 15:30:56,755 : INFO : Machine : Shutting down...
2024-09-17 15:30:56,755 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2024-09-17 15:30:56,755 : ERROR : root : ClearCommError failed (OSError(9, 'Descripteur non valide', None, 6))
Traceback (most recent call last):
  File "C:\Users\brice.rouanet\Documents\mpf\mpf\commands\game.py", line 229, in __init__
    self.machine.run()
  File "C:\Users\brice.rouanet\Documents\mpf\mpf\core\machine.py", line 696, in run
    if not self.initialize_mpf():
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brice.rouanet\Documents\mpf\mpf\core\machine.py", line 684, in initialize_mpf
    self._crash_shutdown()
  File "C:\Users\brice.rouanet\Documents\mpf\mpf\core\machine.py", line 749, in _crash_shutdown
    self._do_stop()
  File "C:\Users\brice.rouanet\Documents\mpf\mpf\core\machine.py", line 740, in _do_stop
    self.shutdown()
  File "C:\Users\brice.rouanet\Documents\mpf\mpf\core\machine.py", line 770, in shutdown
    self._platform_stop()
  File "C:\Users\brice.rouanet\Documents\mpf\mpf\core\machine.py", line 820, in _platform_stop
    hardware_platform.stop()
  File "C:\Users\brice.rouanet\Documents\mpf\mpf\platforms\lisy\lisy.py", line 565, in stop
    self.machine.clock.loop.run_until_complete(self._writer.wait_closed())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 654, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\streams.py", line 364, in wait_closed
    await self._protocol._get_close_waiter(self)
  File "C:\Users\brice.rouanet\Documents\mpfenv\Lib\site-packages\serial_asyncio\__init__.py", line 290, in _poll_read
    if self.serial.in_waiting:
       ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\brice.rouanet\Documents\mpfenv\Lib\site-packages\serial\serialwin32.py", line 259, in in_waiting
    raise SerialException("ClearCommError failed ({!r})".format(ctypes.WinError()))
serial.serialutil.SerialException: ClearCommError failed (OSError(9, 'Descripteur non valide', None, 6))
